name: supercluster
description: A port of MapBox's javascript supercluster library for fast marker clustering.
version: 0.1.0
homepage: https://github.com/rorystephenson/supercluster_dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  kdbush: ^0.0.3
  rbush: ^1.1.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  lints: ^2.0.0
  test: ^1.21.1
