name: supercluster
description: A port of MapBox's javascript supercluster library for fast clustering, with added mutable clustering support.
version: 3.1.0
homepage: https://github.com/rorystephenson/supercluster_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.2
  kdbush: ^0.1.0
  rbush: ^1.1.1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  compute: ^1.0.2
  freezed: ^2.5.4
  lints: ^4.0.0
  test: ^1.25.8
  quiver: ^3.2.1

